### ISSUE TITLE
544307D1 - Dead or Alive 4

### ISSUE THREAD

**Issue by legolas119** [xenia-canary/game-compatibility#330] opened 2024-12-25 20:28 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Wiki page (optional)

https://github.com/xenia-canary/game-compatibility/wiki/...

### Xenia Canary version

https://github.com/xenia-canary/xenia-canary/commit/a6e3d77504064f0f5392134cd55579d619599e41

### Issues

The game works fine but the soundtrack very often is missing. It is always missing in the opening screen (where it is necessary to push START), into the character select screen and into the game mode section. 
During the game, in some stages, sometimes, the soundtrack is missing: sometimes it is present, sometimes is missing and sometimes it is present but during the match it disappears.

### Log

[xenia.zip](https://github.com/user-attachments/files/18247119/xenia.zip)

### Screenshots

it is no necessary to attach screenshots

### Labels

apu-garbage, apu-silent

**Comment by Margen67** [comment] 2024-12-25 20:41
Duplicate of #207

**Closed by Margen67** 2024-12-25 20:41 UTC
