### ISSUE TITLE
494707D4 - Test Drive Unlimited

### ISSUE THREAD

**Issue by OGSmuggy** [xenia-canary/game-compatibility#238] opened 2024-09-19 20:19 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a canary branch. (not MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xenia version

https://github.com/xenia-canary/xenia-canary/commit/3d30b2eec3ab1f83140b09745bee881fb5d5dde2/

### Issues

**None so far.**

### Log

[xenia.zip](https://github.com/user-attachments/files/17066173/xenia.zip)

**Test Drive Unlimited (Europe) Review**

_System Specs_:

- **CPU**: Ryzen 5 3600
- **GPU**: RTX 2070 Super

The game loads seamlessly from the start, with no issues during the intro sequence. Character selection is smooth, and cutscenes play perfectly after choosing your character. Gameplay runs between 30 to 65 FPS based on my specs, though performance may vary depending on your setup. Overall, it delivers a fluid and immersive experience, with only minor dips that don’t impact playability. So far, all missions work flawlessly.

However, when tested on **Xenia Ver. v1.0.2817-master (May 25, 2024)**, the game crashes at the loading screen and does not progress further.

_Xenia-Canary Configuration:_

- **Vertical Sync:** OFF (Forced OFF)

_Tested on: Xenia-Canary Version 5abf67f_canary_experimental (Sep 18th, 2024)_

### Screenshots!

![Screenshot 2024-09-19 204017](https://github.com/user-attachments/assets/d1fbb563-6d2f-4df0-a94b-c4f5a2673471)
![Screenshot 2024-09-19 204047](https://github.com/user-attachments/assets/3d86d654-e1d0-444d-9bd9-d1c08690d36f)
![Screenshot 2024-09-19 204236](https://github.com/user-attachments/assets/d132098c-21b3-4d28-bc01-bfe682fcd3cb)
![Screenshot 2024-09-19 204251](https://github.com/user-attachments/assets/fed8ad41-a9dc-4428-b99b-3a2ecc1d8f00)

###Video

https://github.com/user-attachments/assets/fc7e010b-8dc9-4f3c-a091-0d7924c3f122

### Labels

state-gameplay

**Comment by Margen67** [comment] 2024-09-21 11:06
state-playable only applies if you've played the game from start to finish.

**Comment by Margen67** [comment] 2024-09-26 13:09
Duplicate of #234

**Closed by Margen67** 2024-09-26 13:09 UTC
Labels: state-gameplay
