### ISSUE TITLE
4D5307F1 - Fable 2 GOTY Edition

### ISSUE THREAD

**Issue by EmirHodovic** [xenia-canary/game-compatibility#97] opened 2022-05-19 18:56 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a canary branch. (not MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://marketplace.xbox.com/en-us/product/fable-ii/66acd000-77fe-1000-9115-d8024d5307f1

### Xenia version

https://github.com/xenia-canary/xenia-canary/commit/efb5acc6e3926e7d3d71dfaf00084b48021e9f8c/

### Issues

After closing the game in any way, there is a very high chance that your level will reset back to 0. Also, you may lose all expressions and renown as well.

### Log

[xenia.zip](https://github.com/xenia-canary/game-compatibility/files/8733023/xenia.zip)

### Screenshots

![Screenshot (150)](https://user-images.githubusercontent.com/20261378/169378540-68fa94c5-5560-415c-a4d3-32f6474fb8e1.png)

### Labels

kernel-save-file-errors state-gameplay

**Comment by Margen67** [comment] 2024-09-26 10:24
Duplicate of #74

**Closed by Margen67** 2024-09-26 10:24 UTC
Labels: state-gameplay, kernel-save-file-errors
