### ISSUE TITLE
545408B2 - WWE2K14

### ISSUE THREAD

**Issue by Chaz655** [xenia-canary/game-compatibility#71] opened 2020-11-20 20:33 UTC
[Marketplace](
https://marketplace.xbox.com/en-GB/Product/WWE-2K14/66acd000-77fe-1000-9115-d802545408b2)

Build: detached / canary_new / 7abe6312be6cad35c03b11e4e8de087491eff1c1 on Nov 15 2020

# Issues:
Matches don't work expect royal rumble and the streak (Crashes when match starts) 
Minor Graphical Glitches
30 years of wrestlemania is just a black screen in the matches
Edit: Also it's unoptimized (its only playable on rtx cards basicly)
# Log:
[xenia.zip](https://github.com/xenia-canary/game-compatibility/files/5575853/xenia.zip)

# Screenshot(s):
https://lh3.googleusercontent.com/-qgK0ngQn_NU/X7gme0eWs2I/AAAAAAAAA5E/RPoXxO3UCY4WcKNdEH9n0t5Re5khIZyaACLcBGAsYHQ/image.png

# Labels:
state-menus

**Comment by RetrospectiveYT** [comment] 2020-11-23 10:46
This problem starts with SVR 2011 :( 
But SVR 2011 works on 1.05a ML

**Comment by randprint** [comment] 2020-11-23 10:49
> This problem starts with SVR 2011 :(
> But SVR 2011 works on 1.05a ML

what works in closed source builds you get off youtube is irrelevant, we have no idea how old it is or what is changed since that guy compiled code he picks from canary and master.

**Comment by RetrospectiveYT** [comment] 2020-11-23 12:05
> 
> 
> > This problem starts with SVR 2011 :(
> > But SVR 2011 works on 1.05a ML
> 
> what works in closed source builds you get off youtube is irrelevant, we have no idea how old it is or what is changed since that guy compiled code he picks from canary and master.

most likely, he just disabled saves. in a custom build with a config, you can change the "signin_status = 1" option to 0 and the game will work in the menu, but when you try to enter the match, the emulator crashes. in the official build, the game freezes on the start menu where you need to press "Start".

**Comment by Margen67** [comment] 2024-09-26 10:09
Duplicate of #32

**Closed** 2024-09-26 10:10 UTC
Labels: issue-duplicate
