### ISSUE TITLE
5451083B - 50 cent: Blood On The Sand (50 Cent: BotS)

### ISSUE THREAD

**Issue by betelopson** [xenia-canary/game-compatibility#164] opened 2023-06-13 17:56 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a canary branch. (not MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://marketplace.xbox.com/en-us/product/50-cent-bots/66acd000-77fe-1000-9115-d8025451083b

### Xenia version

https://github.com/xenia-canary/xenia-canary/commit/28c67b93847cfe953205111f4d2fcedd8b10e3bb/

### Issues

Dx12 runs better than Vulkan.
Dx12 makes textures black, but everything looks fine.
Vulkan makes textures transparent.
"d3d12_readback_resolve = false" makes the performance suffer a lot and does not fix anything.
render_target_path_d3d12 = "rov" makes the game run unresponsive and suffer a lot of performance hit.

### Log

[xenia.zip](https://github.com/xenia-canary/game-compatibility/files/11737764/xenia.zip)

### Screenshots

![Clipboard01](https://github.com/xenia-canary/game-compatibility/assets/6606491/9e8fd4a9-4fab-46ca-a738-7713e2594862)
![Clipboard02](https://github.com/xenia-canary/game-compatibility/assets/6606491/f5865459-ceda-438a-b405-abe20516bfc1)
![Clipboard03](https://github.com/xenia-canary/game-compatibility/assets/6606491/5fbf202e-a142-4107-ab33-f892cfbd6a5e)
![Clipboard04](https://github.com/xenia-canary/game-compatibility/assets/6606491/619b8d5e-3ec6-4283-98f4-0df2ece6916d)
![Clipboard05](https://github.com/xenia-canary/game-compatibility/assets/6606491/9d1f210d-ed30-46fe-88a6-da60c5831010)
![Clipboard06](https://github.com/xenia-canary/game-compatibility/assets/6606491/f4db9f89-fe3c-4741-a40e-128b9d07ac08)
![Clipboard07](https://github.com/xenia-canary/game-compatibility/assets/6606491/cb9fa6c4-b9cb-49cf-bcd4-479fbe7a56ec)
![Clipboard08](https://github.com/xenia-canary/game-compatibility/assets/6606491/f8a10da1-13b9-44fe-a5a7-1c998f8b5758)
![Clipboard09](https://github.com/xenia-canary/game-compatibility/assets/6606491/201355ba-5f18-47e3-8453-0b766e6e075f)
![Clipboard10](https://github.com/xenia-canary/game-compatibility/assets/6606491/594676ef-4b5a-4676-a6e9-b8973fc0f0ef)
![Clipboard11](https://github.com/xenia-canary/game-compatibility/assets/6606491/213b311e-b7a5-426e-bc34-6bfafe9f7149)
![Clipboard12](https://github.com/xenia-canary/game-compatibility/assets/6606491/d655358d-8a9b-4c5d-b941-8a3f7b280210)
![Clipboard13](https://github.com/xenia-canary/game-compatibility/assets/6606491/d68f94c0-a5d5-47fb-9838-c53a81711a42)
![Clipboard14](https://github.com/xenia-canary/game-compatibility/assets/6606491/faf15f34-f882-42e5-aa18-f1b156fb9f48)
![Clipboard15](https://github.com/xenia-canary/game-compatibility/assets/6606491/851156bb-3b72-4673-a9ec-ab6233388e45)
![Clipboard16](https://github.com/xenia-canary/game-compatibility/assets/6606491/336aca3c-93dd-4789-acad-56bcb3257277)
![Clipboard17](https://github.com/xenia-canary/game-compatibility/assets/6606491/1a4d0761-c7cc-470b-8aed-2d9c005eee6e)

### Labels

state-playable apu-garbage gpu-drawing-corrupt

**Comment by Margen67** [comment] 2024-09-26 11:57
Duplicate of #104

**Closed by Margen67** 2024-09-26 11:57 UTC
Labels: state-playable, gpu-drawing-corrupt, apu-garbage
