### ISSUE TITLE
55530825 - Naruto The Broken Bond

### ISSUE THREAD

**Issue by majkl7302** [xenia-canary/game-compatibility#113] opened 2022-10-05 18:20 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a canary branch. (not MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://marketplace.xbox.com/en-us/Product/Naruto-The-Broken-Bond/66acd000-77fe-1000-9115-d80255530825

### Xenia version

https://github.com/xenia-canary/xenia-canary/commit/50fce8bdb3c6bee5e5b59b1c587060ff9f271edd

### Issues

50fce8bdb Xenia Canary. 6700 XT. Ryzen 7 2700. Direct3D 12. 

This game has a bit of a graphical glitch issue when; "draw_resolution_scale_x = 2" and "draw_resolution_scale_y = 2". Sometimes it changes the HUE of the game. Top picture shows the problem and the bottom picture is a default. Currently the only way to go around it is by changing the values to "= 1" sacrificing resolution for stability. In my experience it does not affect any frame buffers however we would appreciate a fix to the problem.

Overall best settings to change in the config files would be:
"d3d12_clear_memory_page_state = true"
"vsync = false"
"license_mask = 1"

### Log

[xenia.log](https://github.com/xenia-canary/game-compatibility/files/9718005/xenia.log)

### Screenshots

![Untitled](https://user-images.githubusercontent.com/115105598/194132889-875c2b38-a649-4476-89e2-467625163841.png)
![Untitled1](https://user-images.githubusercontent.com/115105598/194132883-f08acbca-109c-48e5-8645-b7be25faae84.png)

### Labels

gpu-drawing-corrupt state-gameplay

**Comment by Margen67** [comment] 2024-09-26 11:03
Duplicate of #87

**Closed by Margen67** 2024-09-26 11:03 UTC
Labels: state-gameplay, gpu-drawing-corrupt
